# Generated by Django 5.1.6 on 2025-03-07 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="DOB",
            field=models.DateField(blank=True, null=True),
        ),
    ]
