# Generated by Django 5.1.6 on 2025-03-08 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_genre_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="genre",
            name="colour",
            field=models.CharField(default="#00008b", max_length=255),
        ),
        migrations.AlterField(
            model_name="genre",
            name="name",
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
