# Generated by Django 5.1.6 on 2025-04-16 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_friendship_shared_books_alter_friendship_friend_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="friendship",
            old_name="user",
            new_name="from_user",
        ),
        migrations.RenameField(
            model_name="friendship",
            old_name="friend",
            new_name="to_user",
        ),
        migrations.AlterUniqueTogether(
            name="friendship",
            unique_together={("from_user", "to_user")},
        ),
    ]
