# Generated by Django 5.1.6 on 2025-03-09 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_genre_colour_alter_genre_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="genre",
            name="colour",
            field=models.CharField(default="#41ceaa", max_length=255),
        ),
    ]
