# Generated by Django 5.1.6 on 2025-03-18 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_bookrating"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bookrating",
            old_name="book_title",
            new_name="book_id",
        ),
    ]
