# Generated by Django 5.1.6 on 2025-03-18 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_rename_book_title_bookrating_book_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bookrating",
            name="user",
        ),
        migrations.AddField(
            model_name="bookrating",
            name="user_id",
            field=models.IntegerField(default=0),
        ),
    ]
